package sandbox.testproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestObj implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String requesterName;
   private java.math.BigDecimal totalAmount;

   public RequestObj()
   {
   }

   public java.lang.String getRequesterName()
   {
      return this.requesterName;
   }

   public void setRequesterName(java.lang.String requesterName)
   {
      this.requesterName = requesterName;
   }

   public java.math.BigDecimal getTotalAmount()
   {
      return this.totalAmount;
   }

   public void setTotalAmount(java.math.BigDecimal totalAmount)
   {
      this.totalAmount = totalAmount;
   }

   public RequestObj(java.lang.String requesterName,
         java.math.BigDecimal totalAmount)
   {
      this.requesterName = requesterName;
      this.totalAmount = totalAmount;
   }

}