package sandbox.poc.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestObj implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String input;
   private java.lang.String output;
   private java.util.List<java.lang.String> errors;
   private java.lang.String outcome;
   private java.lang.String comments;
   private java.lang.Boolean approved;

   public RequestObj()
   {
   }

   public java.lang.String getInput()
   {
      return this.input;
   }

   public void setInput(java.lang.String input)
   {
      this.input = input;
   }

   public java.lang.String getOutput()
   {
      return this.output;
   }

   public void setOutput(java.lang.String output)
   {
      this.output = output;
   }

   public java.util.List<java.lang.String> getErrors()
   {
      return this.errors;
   }

   public void setErrors(java.util.List<java.lang.String> errors)
   {
      this.errors = errors;
   }

   public java.lang.String getOutcome()
   {
      return this.outcome;
   }

   public void setOutcome(java.lang.String outcome)
   {
      this.outcome = outcome;
   }

   public java.lang.String getComments()
   {
      return this.comments;
   }

   public void setComments(java.lang.String comments)
   {
      this.comments = comments;
   }

   public java.lang.Boolean getApproved()
   {
      return this.approved;
   }

   public void setApproved(java.lang.Boolean approved)
   {
      this.approved = approved;
   }

   public RequestObj(java.lang.String input, java.lang.String output,
         java.util.List<java.lang.String> errors, java.lang.String outcome,
         java.lang.String comments, java.lang.Boolean approved)
   {
      this.input = input;
      this.output = output;
      this.errors = errors;
      this.outcome = outcome;
      this.comments = comments;
      this.approved = approved;
   }

}