package sandbox.poc.model;

import java.util.ArrayList;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class RuleErrors implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.List<java.lang.String> validationErrors;

   public RuleErrors()
   {
   }

   public java.util.List<java.lang.String> getValidationErrors()
   {
      return this.validationErrors;
   }

   public void setValidationErrors(
         java.util.List<java.lang.String> validationErrors)
   {
      this.validationErrors = validationErrors;
   }

   public RuleErrors(java.util.List<java.lang.String> validationErrors)
   {
      this.validationErrors = validationErrors;
   }
   
   public void addValidationError(String error){
       if(validationErrors == null){
           validationErrors = new ArrayList<String>();
       }
       
       this.validationErrors.add(error);
   }

}