package sandbox.poc.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RuleErrors implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.List<java.lang.String> validaitonErrors;

   public RuleErrors()
   {
   }

   public java.util.List<java.lang.String> getValidaitonErrors()
   {
      return this.validaitonErrors;
   }

   public void setValidaitonErrors(
         java.util.List<java.lang.String> validaitonErrors)
   {
      this.validaitonErrors = validaitonErrors;
   }

   public RuleErrors(java.util.List<java.lang.String> validaitonErrors)
   {
      this.validaitonErrors = validaitonErrors;
   }

}