package sandbox.poc.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RuleErrors implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public RuleErrors() {
    }

}