package sandbox;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestObj implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.math.BigDecimal totalAmount;

   public RequestObj()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.math.BigDecimal getTotalAmount()
   {
      return this.totalAmount;
   }

   public void setTotalAmount(java.math.BigDecimal totalAmount)
   {
      this.totalAmount = totalAmount;
   }

   public RequestObj(java.lang.String name, java.math.BigDecimal totalAmount)
   {
      this.name = name;
      this.totalAmount = totalAmount;
   }

}